const SET_FILTERS = 'SET_FILTERS';
const SET_GENDER = 'SET_GENDER';
const SET_BREED_IDS = 'SET_BREED_IDS';
const SET_CITY_ID = 'SET_CITY_ID';
const SET_COLOR_IDS = 'SET_COLOR_IDS';
const SET_SIZE_ID = 'SET_SIZE_ID';
const SET_PRICE_FROM = 'SET_PRICE_FROM';
const SET_PRICE_TO = 'SET_PRICE_TO';
const SET_HAS_PEDIGREE = 'SET_HAS_PEDIGREE';

const ADD_FAVORITE_ITEM = 'ADD_FAVORITE_ITEM';
const REMOVE_FAVORITE_ITEM = 'REMOVE_FAVORITE_ITEM';
const SET_FAVORITE_ITEMS = 'SET_FAVORITE_ITEMS';

export {SET_FAVORITE_ITEMS,REMOVE_FAVORITE_ITEM,ADD_FAVORITE_ITEM,SET_FILTERS,SET_GENDER,SET_BREED_IDS,SET_CITY_ID,SET_COLOR_IDS,SET_SIZE_ID,SET_PRICE_FROM,SET_PRICE_TO,SET_HAS_PEDIGREE}